version: 2.1

jobs: # basic units of work in a run
  build:
    working_directory: "~/percyAppTest"
    docker: # use the Docker executor
      # CircleCI node images available at: https://hub.docker.com/r/circleci/node/
      - image: circleci/node:12
    environment:
      - CHROME_BIN=  "/usr/bin/google-chrome"
    steps: # steps that comprise the `build` job
      - checkout # check out source code to working directory
      - run: cd percyAppTest && npm install
      # - run: cd percyAppTest && npm run test
