version: 2.1

dependencies:
  pre:
    - sudo npm install angular-cli@latest -g

default_steps: &default_steps
  steps:
    - checkout
    - run: cd percyAppTest && npm ci && sudo npm install angular-cli -g && ng build
    - run: cd percyAppTest && npm run snapshots

jobs: # basic units of work in a run
  build:
    working_directory: "~/percyAppTest"
    docker: # use the Docker executor
      # CircleCI node images available at: https://hub.docker.com/r/circleci/node/
      - image: circleci/node:12-browsers
    environment:
      - CHROME_BIN=  "/usr/bin/google-chrome"
      - PERCY_ENABLE: 0
    <<: *default_steps
  percy_test:
    docker:
      - image: circleci/node:10-browsers
    <<: *default_steps

workflows:
  version: 2
  test:
    jobs:
      - build
      - percy_test
